name: Run tests in Docker

on:
  push:
    branches-ignore: [dev]
  pull_request:
  workflow_dispatch:

jobs:
  build_test_image:
    name: Run tests and linters in Docker container
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      redis:
        image: redis:7
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379


    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --tag ${{ github.event.repository.name }}:0.0

      - name: Run tests in Docker container
        run:
          docker run
          -e PYTHONPATH=.
          -e PYTEST=true
          -e REDIS_HOST=redis
          -e REDIS_PORT=6379
          --network ${{ job.container.network }}
          ${{ github.event.repository.name }}:0.0
          python -m pytest --disable-warnings

      - name: Run linters in Docker container
        run:
          docker run
          ${{ github.event.repository.name }}:0.0
          /bin/sh -c 'git init . && git add . && pre-commit run --all-files'

      - name: Run mypy in Docker container
        run:
          docker run
          ${{ github.event.repository.name }}:0.0
          mypy --config-file mypy.ini -p src
